# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d77ad28dbc5c06fefb40e99d1e9ac5ac4d6ddcf4225da1c1d93998b319826d6d38ce45586acd7c9ceeb54f79d1d0620a5ed17a52b1279e006f37b942bbef65b

test:
  secret_key_base: c89547ccc4990a4496c916ed430cbf7bf3b77ed1e4f49f15944c407a0788df71292a27bd66d956ff62e6da1f5b5cfa7a6a32d6222aaba9f66af3a6f41cdfb250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
